### ISSUE TITLE
@tanstack/react-store@0.9.1 causes atom?.get is not a function runtime error (works in 0.8.1)

### ISSUE THREAD

**Issue by jeanzuck** [TanStack/store#280]
### Describe the bug

After upgrading @tanstack/react-store from 0.8.1 to 0.9.1, the application crashes in the browser at runtime with:

`Uncaught TypeError: atom?.get is not a function at @tanstack_react-store.js:638:70 at mountSyncExternalStore (react-dom_client.js:6001:26) at Object.useSyncExternalStore (react-dom_client.js:18758:18) at useStore (@tanstack_react-store.js:639:86) at useRouterState (useRouterState.js:20:10)`

### Steps to Reproduce the Bug or Issue

**Steps to Reproduce**

**Option 1 — Using the provided reproduction repository**

1. Clone the repository:

   ```
   git clone https://github.com/jeanzuck/reproduce-tanstack-react-store-0.9.1
   ```
2. Install dependencies:

   ```
   pnpm install
   ```
3. Start the development server:

   ```
   pnpm dev
   ```
4. Open `http://localhost:3000` and observe the console error.

**Option 2 — Reproducing in a fresh project**

1. Create a new TanStack Start project:

   ```
   pnpm create @tanstack/start@latest
   ```
2. Install `@tanstack/react-store`:

   ```
   pnpm add @tanstack/react-store
   ```
3. Use the example code from the TanStack Store React Quick Start documentation.
4. Run the application:

   ```
   pnpm dev
   ```
5. Open `http://localhost:3000` and observe the console error.

### Expected behavior

The app should run normally without runtime errors, consistent with behavior in @tanstack/react-store@0.8.1.

### Platform

- OS: Windows 11
- Browser: Chrome, Edge

**Comment by colinchadwick** [comment]
Can confirm. Having the same issue.

**Comment by kimthompson** [comment]
Me too, on a fresh install

**Comment by rafcontreras** [comment]
Looks like `better-auth` depends on atom so it is quite a breaking change

**Comment by jwaltz** [comment]
I don't have `store` as a dependency but I am using `@tanstack/react-router` and `v1.161.3` bumped its dependency on `store` to `0.9.1` and I've been getting odd errors since like:

`TypeError: Cannot read properties of undefined (reading 'atom')`

When I downgrade to `v1.161.1` (the previous published release) of `@tanstack/react-router` (which uses `v0.8.0` of `store`) the issues are resolved.
